#!/bin/bash
#SBATCH --partition=cpu
#SBATCH --mem-per-cpu=10G
#SBATCH --time=0-1:00
#SBATCH --tasks=1 

#####
# INPUT files
#####


#Path to the script to run
scriptpath=$1

	
# extract phenotype IDs and locus to analyse
traits=$2
locus=$3


#Set analysis options
LDREFERENCE=$4		#File path and prefix for LD reference plink-binary files
outpath=$5		#File path and prefix for the output files.
sumplots=$6		#Which summary plots to generate

#Path to plink executable
plinkpath=${7}

#Which analyses to run
runMode=${8}
	

tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)

cd  $tmp_dir

#Print to log that a new analysis loop has begun
printf "########################\nAnalysing traits: ${traits} at locus: ${locus}\n"

echo "Running main colocalisation analysis script"
	
#This script harmonises summary statistics, performs finemapping, and then colocalisation analysis
Rscript ${scriptpath}/colocaliseRegion.R \
		--LDreference $LDREFERENCE \
		--plink $plinkpath \
		--set_locus $locus \
		--runMode $runMode \
		--gene_tracks 40 \
		--restrict_nearby_gene_plotting_source "HGNC Symbol" \
		--force_matrix FALSE \
		--finemap_refine FALSE \
		--finemapQC_handleBetaFlips drop \
		--finemap_CScoverage 0.95 \
		--out $outpath \
		--traits $traits \
		--GWASconfig ${scriptpath}/GWAS_samples.txt \
		--helperFunsDir "${scriptpath}/helper_functions"
		
echo "Running GWAS summary figure script"
		
#This script takes harmonised summary statistics as input and plots comparisons across the measures indicated in --GWASsumplots across pairs of GWAS summary statistics
Rscript ${scriptpath}/gwasSummaryPlotter.R \
		--traits $traits \
		--harmonisedSumstats ${outpath}_coloc/data/datasets/harmonised_sumstats.csv \
		--GWASconfig ${scriptpath}/GWAS_samples.txt \
		--GWASsumplots $sumplots \
		--GWASsumplots_onefile FALSE \
		--GWASsumplots_incfinemapping TRUE \
		--helperFunsDir "${scriptpath}/helper_functions" \
		--outdir "${outpath}_coloc/plots" 
		
	



rm -rf $tmp_dir
