#!/bin/bash
#SBATCH --partition=cpu
#SBATCH --mem-per-cpu=10G
#SBATCH --time=0-1:00
#SBATCH --tasks=1 

#####
# INPUT files
#####


#Path to the script to run
scriptpath=$1

	
# extract phenotype IDs and locus to analyse
traits=$2
locus=$3
GWASinfo=$4


#Set analysis options
LDREFERENCE=$5		#File path and prefix for LD reference plink-binary files
outpath=$6		#File path and prefix for the output files.
sumplots=$7		#Which summary plots to generate
sumplots_onefile=$8 	#Logical indicating whether to put summary plots all into one file

#Path to plink executable
plinkpath=${9}

#Which analyses to run
runMode=${10}
	

tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)

cd  $tmp_dir

#Print to log that a new analysis loop has begun
printf "########################\nAnalysing traits: ${traits} at locus: ${locus}\n"
	

Rscript $scriptpath \
		--LDreference $LDREFERENCE \
		--plink $plinkpath \
		--set_locus $locus \
		--runMode $runMode \
		--GWASsumplots $sumplots \
		--GWASsumplots_onefile $sumplots_onefile \
		--gene_tracks 40 \
		--restrict_nearby_gene_plotting_source "HGNC Symbol" \
		--force_matrix FALSE \
		--out $outpath \
		--traits $traits \
		--GWASconfig ${GWASinfo} \
		--helperFunsDir "$(dirname ${scriptpath})/helper_functions"




rm -rf $tmp_dir
